### ISSUE TITLE
[Feature Request] Questions about the main window

### ISSUE THREAD

**Issue by caitou2019** [AllenDang/giu#525] opened 2022-06-26 16:54 UTC
### Related problem

I set the main window to be borderless (actually I don't want the main window). 
Then I want to press and hold the "good" imgui window to drag.
At present, I can't drag.
![image](https://user-images.githubusercontent.com/47804016/175825202-eafe9056-61ea-4e50-a1d3-32d9af9825ec.png)

This is my code and effect:
![image](https://user-images.githubusercontent.com/47804016/175824789-d5561fc3-754d-4363-bff9-409564822876.png)

![image](https://user-images.githubusercontent.com/47804016/175824876-48f3a55c-d0b7-441b-b966-43bfed910a62.png)
English annotation text of effect picture "I want to press and hold here to drag the window anywhere on the screen"

Thanks your help！！

### Your request

1.Hide main window（Maybe that can replace it with no border）
2.Full screen drag and drop for sub windows

### Alternative solution

It may be possible to move the main window by getting the drag message of the child window and passing it to the main window.

### Additional context

package imgui

import (
	"fmt"
	g "github.com/AllenDang/giu"
	"image/color"
)

var wnd *g.MasterWindow

func Load() {
	flag := g.MasterWindowFlagsTransparent | g.MasterWindowFlagsNotResizable | g.MasterWindowFlagsFloating | g.MasterWindowFlagsFrameless
	wnd = g.NewMasterWindow("Hello world", 400, 200, flag)
	wnd.SetBgColor(color.RGBA{})
	wnd.SetPos(800, 200)
	wnd.Run(loop)
}

func loop() {
	flag := g.WindowFlagsNoResize | g.WindowFlagsNoMove | g.WindowFlagsAlwaysUseWindowPadding | g.WindowFlagsAlwaysAutoResize
	g.Window("good").Flags(flag).Size(400, 200).Layout(
		g.Label("Hello world from giu"),
		g.Row(
			g.Button("Click Me").OnClick(onClickMe),
			g.Button("I'm so cute").OnClick(onImSoCute),
		),
	)

}

func onClickMe() {
	fmt.Println("Hello world!")
}

func onImSoCute() {
	fmt.Println("Im sooooooo cute!!")
}

**Comment by gucio321** [comment] 2022-06-27 16:33
Take a look on examples/transparent

**Comment by caitou2019** [comment] 2022-06-29 03:15
I looked at examples/transparent. The effect is very similar, but the child window cannot move out of the range of the main window. What I want is that the child window will not be limited by the range of the parent window.

this is official C++ examples, githua branch is docking. The effect I want is this.
The effect is shown in the following figure:
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/47804016/176343221-67a304b5-a0a1-490a-84ff-9fdb1a633771.png">

**Comment by gucio321** [comment] 2022-06-29 04:35
Well i don't exactly know what docking branch is but as far as i remember implementing this stuff is one of the issues @AllenDang is going to face with at first. If the feature you want is available only on the docking branch of imgui it isn't probably implemented in giu yet

**Comment by caitou2019** [comment] 2022-06-30 01:55
ok, thank u, i will wait for your integration.

**Comment by gucio321** [comment] 2022-06-30 06:15
As far as i can see it is a duplicate of #512

**Comment by MPWrobel** [comment] 2022-08-10 20:24
> I just got an idea: How about making a master window full screened, transparent and decorationless, than just add a normal giu.Window?

Then we need mouse passthrough I think. Otherwise otherwise you won't be able to interact with anything outside the app

**Comment by gucio321** [comment] 2023-05-09 19:23
ok, I'm going to close this as duplicate of our Docking issue #512 
In case of "  mouse passthrough" see #559 (I think it is the same feature)

**Closed by gucio321** 2023-05-09 19:23 UTC
Labels: enhancement
