### ISSUE TITLE
Using -race flag throws runtime checkptr errors

### ISSUE THREAD

**Issue by bashthekeys** [AllenDang/giu#464] opened 2022-02-25 09:02 UTC
When running with -race flag there are checkptr errors thrown in the code, this happens with data passed to the imgui TextureID function and Vertexbuffer data. Similar issues are reported on the imgui repo, and are claimed fixed.

**Comment by gucio321** [comment] 2022-02-25 17:43
duplicate of #30

**Comment by AllenDang** [comment] 2022-02-28 03:01
@gucio321 I will make some time and fix this soon.

**Comment by gucio321** [comment] 2022-07-12 06:37
@bashthekeys check again it  works now!

**Comment by bashthekeys** [comment] 2022-07-12 09:32
Thank you, brilliant it’s working :) Enabled me to track and fix some data races in my code.

Will there be any focus on fixing the race conditions it now shows in imgui ?

**Closed** 2022-07-12 09:35 UTC
