### ISSUE TITLE
[Feature Request] Transparant example, draggable window

### ISSUE THREAD

**Issue by s3rj1k** [AllenDang/giu#513] opened 2022-05-28 20:54 UTC
Would be nice to see how to implement mouse draggable window in transparent example.

**Comment by gucio321** [comment] 2022-06-05 11:31
you mean something like this?
![image](https://user-images.githubusercontent.com/73652197/172048385-cad45818-34de-4e4f-8880-f6f4fe48d696.png)

**Comment by s3rj1k** [comment] 2022-06-05 12:41
@gucio321 I was thinking about dragging main window, the one that gets decorated in your example.

**Comment by s3rj1k** [comment] 2022-06-30 08:58
@gucio321 I was considering a case for one window application, that has no WM decoration but window still can be moved around.

Similar to Firefox picture in picture window that can be moved around by clicking and holding on a window content.

**Comment by gucio321** [comment] 2022-06-30 11:14
well, I see what you mean. I think that it is the same problem as in #525 - you probably need docking to do this.

**Comment by s3rj1k** [comment] 2022-06-30 11:30
Seems related yes, the benefit of transparent example with this use case is that it will be possible to draw some custom shape window.

**Comment by gucio321** [comment] 2023-05-09 19:25
@s3rj1k like in #525:
Duplicate of #512 and related to #559

**Closed by gucio321** 2023-05-09 19:25 UTC
Labels: enhancement
