### ISSUE TITLE
v0.8.0: SetTextureMagFilter/SetTextureMinFilter no longer present

### ISSUE THREAD

**Issue by greenthepear** [AllenDang/giu#851] opened 2024-09-16 16:04 UTC
Back in v0.7.0 one could set texture magnification/minification filter through the context, how can be that done now? The old way:

```go
giu.Context.GetRenderer().SetTextureMagFilter(giu.TextureFilterNearest)
```

This issue might be suitable for cimgui-go instead I guess? Maybe #755 could also be revisited.

**Comment by gucio321** [comment] 2024-09-16 16:13
Hi!
yes, this has to be added in cimgui-go first.
Tbh, Im focused on a bit different things in cimgui-go right now (https://github.com/AllenDang/cimgui-go/issues/25)
But I keep in mind this has to be done ;-)
Let me close this as a duplicate of #755 

Btw, contributions to cimgui-go and here are welcome! ;-)

**Closed by gucio321** 2024-09-16 16:13 UTC
