### ISSUE TITLE
Unsafe pointer arithmetic

### ISSUE THREAD

**Issue by pztrn** [AllenDang/giu#30] opened 2020-03-03 10:42 UTC
I've compiled application with ``-race`` and it crashed right before showing up GUI.

```
fatal error: checkptr: unsafe pointer arithmetic

goroutine 1 [running, locked to thread]:
runtime.throw(0xce6324, 0x23)
        /usr/lib/go/src/runtime/panic.go:1112 +0x72 fp=0xc00011fa18 sp=0xc00011f9e8 pc=0x483d12
runtime.checkptrArithmetic(0x1, 0x0, 0x0, 0x0)
        /usr/lib/go/src/runtime/checkptr.go:24 +0xce fp=0xc00011fa48 sp=0xc00011fa18 pc=0x456fde
github.com/AllenDang/giu/imgui.TextureID.handle(...)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/imgui/TextureID.go:24
github.com/AllenDang/giu/imgui.FontAtlas.SetTextureID.func1(0x27280e0, 0x1)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/imgui/FontAtlas.go:174 +0x78 fp=0xc00011fa88 sp=0xc00011fa48 pc=0xa3c3c8
github.com/AllenDang/giu/imgui.FontAtlas.SetTextureID(0x27280e0, 0x1)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/imgui/FontAtlas.go:174 +0x43 fp=0xc00011faa8 sp=0xc00011fa88 pc=0xa35683
github.com/AllenDang/giu/imgui.(*OpenGL3).createFontsTexture(0xc000074230)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/imgui/RendererOpenGL3.go:338 +0x3e5 fp=0xc00011fb50 sp=0xc00011faa8 pc=0xa289f5
github.com/AllenDang/giu/imgui.(*OpenGL3).createDeviceObjects(0xc000074230)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/imgui/RendererOpenGL3.go:292 +0xd26 fp=0xc00011fcc8 sp=0xc00011fb50 pc=0xa28256
github.com/AllenDang/giu/imgui.NewOpenGL3(0x2724368, 0x3fe00000, 0xb, 0x258, 0x1f4)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/imgui/RendererOpenGL3.go:46 +0x1f5 fp=0xc00011fd50 sp=0xc00011fcc8 pc=0xa25485
github.com/AllenDang/giu.NewMasterWindowWithBgColor(0xcd52c1, 0xb, 0x258, 0x1f4, 0x1, 0xc00011fec0, 0x0, 0x7fd2ff3d8108)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/MasterWindow.go:54 +0x263 fp=0xc00011fe30 sp=0xc00011fd50 pc=0xa53723
github.com/AllenDang/giu.NewMasterWindow(...)
        /home/pztrn/projects/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20200210105846-9cbca4cde9f2/MasterWindow.go:25
```

**Comment by AllenDang** [comment] 2020-03-04 02:37
It's a wrapper for a C pointer. I need to dig a little bit more about what -race does. BTW, it works fine in normal mode.

**Comment by pztrn** [comment] 2020-03-04 07:02
Yep, I agree, but this will prevent running application with ``-race`` for race detection which is not good IMO.

**Comment by AllenDang** [comment] 2020-03-04 07:54
@pztrn Yes, you got the point. I will dig it out.

**Comment by AllenDang** [comment] 2020-03-07 06:13
This issue caused by converting uintptr to a C void* pointer. Anyone knows how to avoid this crash?

**Comment by ryn1x** [comment] 2020-06-18 18:55
I am getting this same error. This prevents me from using the `-race` tool.  Seems like a pretty big issues since there is a lot of concurrency going on in a typical GUI application and `-race` is really needed.

**Comment by AllenDang** [comment] 2020-06-19 01:27
@ryn1x I'll take a look on this deeply this time. This is truly a big issue.

**Comment by yarcat** [comment] 2020-08-12 20:48
The trick here is that there should be no `unsafe.Pointer`. All `void*` should be replaced with `uintptr_t` from `<stdint.h>` (or `<cstdint>`). If `uintptr` -to- `void*` conversion is required, it should be done on C side, not on Go.

Check [this example commit](https://github.com/yarcat/giu/commit/a9b8709df259ae6167d74eb5a883dd755c62b89e), which allows to bypass first of the failures demonstrated by using `-race` option passed to `go build/run`. 

It's quite tedious and non-rewarding work. But I'll do my best to help with it.

**Comment by yarcat** [comment] 2020-08-12 22:30
Unfortunately they also have this in [go-gl](https://github.com/go-gl/example/issues/72) which makes it harder to fix as the rabbit hole is much deeper than I hoped.

**Comment by AllenDang** [comment] 2020-08-13 02:24
@yarcat Yeah, I met the same upstream problem last time when I try to fix this.

**Comment by kettek** [comment] 2020-10-07 19:47
To note, the fork @ https://github.com/neclepsio/gl has some variant function calls that, afaik, should problems stemming from unsafe.Pointer use. I've experimentally tried using it (along with changing some of the imgui C interface) and it fixed the pointer arithmetic problems.

**Comment by AllenDang** [comment] 2020-10-08 06:51
@kettek Wow! Can you make a PR?

**Comment by kettek** [comment] 2020-10-08 21:51
Sure. It ended up being part of my attempts to do per-texture filtering, so I'll separate it from that first.

**Comment by ravicheema** [comment] 2020-11-04 14:43
Unfortunately this issue is a bit of show stopper for a concurrent GIU application, where using -race to catch data race issue is very important. Will this be resolved soon?

**Comment by AllenDang** [comment] 2020-11-05 02:58
@ravicheema Cannot promise when, but I'm keep trying to fix it everyday.

**Comment by kettek** [comment] 2020-11-06 22:08
I'll attempt to make a PR this weekend integrating the changes I had experimented with last month.

**Comment by kettek** [comment] 2020-11-10 00:32
See https://github.com/AllenDang/giu/pull/83

There are still issues with actual race conditions but this PR fixes the unsafe pointer arithmetic problem.

**Comment by ravicheema** [comment] 2020-11-11 14:51
WORK AROUND - Go +1.14 has added `-d=checkptr` which adds instrumentation to check that Go code is following `unsafe.Pointer` safety rules when `-race` is specified. This can be disabled with `gcflags=all=-d=checkptr=0`

Use the following to perform data race condition checks but disable unsafe.Pointer safety rules,
`go run -race -gcflags=all=-d=checkptr=0 .`

Not ideal but it is a work around.

**Comment by dertseha** [comment] 2021-04-30 19:41
Hello there!
I bring greetings from `go-gl/gl`, where a PR ( go-gl/gl#135 ) has landed that allows to handle `checkptr` issues - for the most common GL calls.

For example, instead of calling `gl.VertexAttribPointer()` the code needs to call the newly available `gl.VertexAttribPointerWithOffset()` - Note the change in type of the last argument.

There are a few more overloads with `WithOffset` in their name. There might be more functions that need this treatment - see READMEs of `go-gl/glow` and `go-gl/gl` for more details on `checkptr` and overloads in case more function overloads are needed.

In general, any use of `gl.PtrOffset()` is discouraged - a future update has it marked as deprecated.

I have not reviewed the giu code, my proposal is to remove any use of `PtrOffset()` and ensure direct use of `uintptr` type - and in case overloads are needed, use those or please report them missing.

Also, as the maintainer of imgui-go, I can report that the original issue about TextureID has also long been fixed.

**Comment by kettek** [comment] 2021-04-30 23:47
Great to hear! I will rework the changes in PR #83, as that used a fork of go-gl/gl that implemented WithOffset, to use the updated go-gl/gl version as well as to reintegrate imgui-go's TextureID fixes.

Thanks for the update!

**Comment by AllenDang** [comment] 2021-05-06 03:19
@dertseha Wow! This is a great news! @kettek Thanks for your great work! Looking forward for your PR.

**Comment by gucio321** [comment] 2021-10-05 16:45
@AllenDang it seems like upstream imgui-go doesn't have this issue anymore. I tried to run inky blackness/imgui-go-examples example and it went clean.

**Comment by AllenDang** [comment] 2021-10-08 09:02
@gucio321 I'll check it out and fix it soon.

**Comment by runrc** [comment] 2022-01-31 11:17
Any updates on this issue?

**Comment by gucio321** [comment] 2022-03-22 08:45
well so like I said any example from inkyblackness/imgui-g-examples works well with -race so i suppose that @AllenDang needs to change something inside of AllenDang/imgui-go however idk what is the point there.

**Comment by AllenDang** [comment] 2022-03-22 10:48
@gucio321 Yes, it's the root cause. I'm thinking about to use cimgui (as it is auto-generated and easy to sync the changes from imgui) to recreate the binding, might need more time to evaluate.
And sorry for the delay, :P

**Comment by AllenDang** [comment] 2022-03-22 11:48
@pztrn @gucio321 @runrc I got it fixed, finally... 
@dertseha Thanks for your code, they guide me step by step to right point.

**Closed** 2022-03-22 12:23 UTC
Labels: help wanted
