### ISSUE TITLE
DPI scale - unexpected behavior

### ISSUE THREAD

**Issue by aleksandrzhiliaev** [AllenDang/giu#29] opened 2020-02-16 23:07 UTC
This commit https://github.com/AllenDang/giu/commit/27ecca73d762cacc8bdd23e12dd18c07b76623ab
breaks UI rendering on high monitor resolution.

Before:
<img width="701" src="https://user-images.githubusercontent.com/12209346/74614577-414fc300-5119-11ea-9a20-5549c26307de.png">

After:
<img width="712" src="https://user-images.githubusercontent.com/12209346/74614584-50cf0c00-5119-11ea-9d7f-a895554a1c47.png">

**Comment by AllenDang** [comment] 2020-02-17 04:27
@aleksandrzhiliaev Can you help me to do a test? What's the return value of giu.Context.GetPlatform().GetContentScale()?
It seems the UI is zoomed twice. 
The DPI scale works well on both Windows and MacOS, what desktop OS you are using?

**Comment by aleksandrzhiliaev** [comment] 2020-02-17 08:21
> giu.Context.GetPlatform().GetContentScale()

It returns 2

I use Mac OS Mojave and Catalina.

**Comment by AllenDang** [comment] 2020-02-17 12:23
@aleksandrzhiliaev I see. I will test it on Mac. Get back to you soon.

**Comment by AllenDang** [comment] 2020-02-17 12:37
@aleksandrzhiliaev Can you help to test now? I used to get the content scale factor from primary monitor. Now I changed it to get from current monitor where the master window is displayed.

**Comment by aleksandrzhiliaev** [comment] 2020-02-17 14:50
@AllenDang, it is still 2

**Comment by remeh** [comment] 2020-02-22 08:40
I can report having the same issue. `giu.Context.GetPlatform().GetContentScale()` also returns 2 (macOS, Mojave).

**Comment by AllenDang** [comment] 2020-02-26 07:52
@remeh @aleksandrzhiliaev I just reproduce this bug on Mac. I will get it fixed soon.

**Comment by AllenDang** [comment] 2020-02-26 08:05
@aleksandrzhiliaev @remeh It should be fixed now.

**Comment by remeh** [comment] 2020-02-26 12:58
Hey! It's getting better but there is still some issues.

First, there is a discrepancy in some padding if an external monitor is plugged in and when there is not:

<img width="491" alt="Capture d’écran 2020-02-26 à 13 48 08" src="https://user-images.githubusercontent.com/1798689/75346439-ffecaf80-589e-11ea-8be9-7c92f913c5e2.png">

The left one is the app started when no external monitor was plugged in. I've then plugged a monitor, started a second instance of it and this is what you can observe in the right part of the screenshot. Both are displayed in the Mac screen (scale=2)

Also, there is a difference of size in some widgets when I'm moving my app between a screen with scale=2 and a screen with scale=1. For example in the ProgressBar, I think this is due to this:

https://github.com/AllenDang/giu/blob/master/Widgets.go#L616-L617

This is my app while displayed on my external monitor (scale=1)
![Capture d’écran 2020-02-26 à 13 47 57](https://user-images.githubusercontent.com/1798689/75346798-c36d8380-589f-11ea-887e-bd036e2b08f8.png)
and when moved to the Mac screen (scale=2)
<img width="238" alt="Capture d’écran 2020-02-26 à 13 56 10" src="https://user-images.githubusercontent.com/1798689/75346815-ca949180-589f-11ea-9c99-7a93659c3155.png">

Hope this helps.

**Comment by AllenDang** [comment] 2020-02-27 06:32
@remeh Yes, it's very helpful. I notice that MacOS will auto scale UI element, both font and other size, so I may not need to scale them again. I'll test it tomorrow when I got a Macbook by my side.
Get back to you soon.

**Comment by pztrn** [comment] 2020-03-12 06:15
Any updates on this? Just tried to compile with latest master and jeez, everything is so big...

**Comment by AllenDang** [comment] 2020-03-12 07:02
@pztrn Which platform your are running? Everything is so big?

**Comment by pztrn** [comment] 2020-03-12 07:05
Sorry, it's macOS (Mojave and Catalina).

**Comment by AllenDang** [comment] 2020-03-12 07:08
@pztrn Try it now. It should be fixed.

**Comment by pztrn** [comment] 2020-03-12 07:48
@AllenDang well, nope :(

After doing some testing I was able to get properly scaled (or, better say, unscaled) and more-or-less-good loking fonts by commenting out ``imgui.DPIScale = scale`` in ``MasterWindow.go``, but checkboxes, menus, buttons and paddings are too big yet comparing to Linux/Windows rendering.

**Comment by AllenDang** [comment] 2020-03-12 07:59
@pztrn How about now? I disabled the content scale in Platform level.

**Comment by pztrn** [comment] 2020-03-12 08:03
@AllenDang now it matches Windows and Linux 👍

**Closed** 2020-03-12 08:29 UTC
